### ISSUE TITLE
Code cleanup and minor bug fixes

### ISSUE THREAD

**Issue by SarahKurek** [UniRegensburg/unsere-app-fur-die-universitat-regensburg-bib-buddy#152]
- [x] check for TODOs
- [x] sortFunction access modifier -> first private -> protected -> public
- [x] fix Java Code Warnings; Android Warnings & Typos are ignored due to limited time (warnings mainly because of typos, icons and spelling errors)
- [x] fix headers everywhere
- [x] consistent Button names -> btn
- [x] in on create view in Fragments consistent code structure
- [x] consistent header for notes and add book with ISBN typing.
- [x] consistent enums
- [x] using model instead of DAO: in BookOnlineFragment, BookBarcodeScanner and ImportBibTex?
- [x] either lamda function or new on click listener
- [x] check for unused code
- [x] check for deprecated functions: 3 deprecated functions which will be ignored due to limited time
- [x] check for unused imports
- [x] error handling (remove System.out.println, ...)
- [x] requireActivity instead of getActivity where possible in all Fragments
- [x] requireContext instead of getContext where possible in all Fragments
- [x] renaming the classes
- [x] consistent comments?
- [x] optimize context and view usage
- [x] create getter and setter for public members in Main Activity
- [x] assert bundle != null if missing -> because it is faster; we are aware that it is not consistent with other parts of our code

**Comment by claudia3** [comment]
Code Cleanup Checklist Classes
- [ ] ApiReader
- [ ] Author
- [ ] AuthorDao
- [ ] AuthorFormFragment
- [ ] AuthorFragment
- [ ] AuthorItem
- [ ] AuthorRecyclerView
- [ ] AuthorRetriever
- [ ] BibTexKeys
- [ ] Book
- [ ] BookBarcodeScanner
- [ ] BooDao
- [ ] BookFormFragment
- [ ] BookFragment
- [ ] BookItem
- [ ] BookModel
- [ ] BookNotesView
- [ ] BookNotesViewModel
- [ ] BookOnlineFragment
- [ ] BookRecyclerViewAdapter
- [ ] DatabaseHelper
- [ ] DataValidation
- [ ] DateConverter
- [ ] ExportBibTex
- [ ] HelpFragment
- [ ] HomeFragment
- [ ] ImportBibTex
- [ ] ImprintFragment
- [ ] InterfaceAuthorDao
- [ ] InterfaceBookDao
- [ ] InterfaceNoteDao
- [ ] InterfaceShelfDao
- [ ] InterfaceTagDao
- [ ] IsbnRetriever
- [ ] LibraryFormFragment
- [ ] LibraryFragment
- [ ] LibraryItem
- [ ] LibraryKeys
- [ ] LibraryModel
- [ ] LibraryRecyclerViewAdapter
- [ ] MainActivity
- [ ] Note
- [ ] NoteAudioItem
- [ ] NoteDao
- [ ] NoteItem
- [ ] NoteModel
- [ ] NoteRecyclerViewAdapter
- [ ] NotesFragment
- [ ] NoteTextItem
- [ ] NoteTypeLut
- [ ] RichTextEditor
- [ ] RichTextEditorBulletSpan
- [ ] RichTextEditorPart
- [ ] RichTextEditorQuoteSpan
- [ ] SearchFragment
- [ ] SearchItem
- [ ] SearchItemType
- [ ] SearchModel
- [ ] SearchRecyclerViewAdapter
- [ ] SeekBarListener
- [ ] Shelf
- [ ] ShelfDao
- [ ] ShelfItem
- [ ] SortableItem
- [ ] SortCriteria
- [ ] SortDate
- [ ] SortDialog
- [ ] SortName
- [ ] StorageKeys
- [ ] Tag
- [ ] TagDao
- [ ] TextNoteEditorFragment
- [ ] UriUtils
- [ ] UriUtilsKeys
- [ ] VoiceNoteEditorFragment
